name: Bug Report
description: Report a bug in nectar-ui
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: A clear description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Import component...
        2. Pass these props...
        3. See error...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: nectar-ui version
      placeholder: "0.1.0"
    validations:
      required: true
